# Project information
site_name: "DS"
site_author: "Grupo 03"
site_url: "https://sfernandos.github.io/Teste-G3/"

# Repository
repo_name: "Agenda"
repo_url: "https://sfernandos.github.io/Teste-G3/"

theme: readthedocs

# Content Menu
nav:
    - Projeto:
        - Requisitos:
        - alguma coisa: "nadinha.md"
    - Design:
        - Identidade visual: "project/visual-identity.md"
        - Protótipo de baixa fidelidade: "project/low-prototype.md"
        - Protótipo de média fidelidade: "project/mid-prototype.md"
        - Protótipo de alta fidelidade: "project/high-prototype.md"
        - Teste de usabilidade: "project/usability-test.md"
    - Gerência:
        - Plano metodológico:
        - Plano metodológico: "management/methodology-plan.md"
        - Plano de comunicação: "management/communication-plan.md"
      - Roadmap do Produto: "management/product-roadmap.md"
      - Reuniões com Usuários:
        - Reunião 1: "management/po-meetings/meeting-1.md"
    - Pontos de Controle:
        - Ponto de Controle 1: "releases/release-1.md"